#index:
#    path: /
#    controller: App\Controller\DefaultController::index

MyApp:
    path: /Accueil
    controller: App\Controller\TesteController::index

LuckyController:
    path: /lucky/number
    controller: App\Controller\LuckyController::number